load("@rules_shell//shell:sh_library.bzl", "sh_library")
load("@rules_shellcheck//:def.bzl", "shellcheck_test")

sh_library(
    name = "scripts",
    srcs = glob(["src/**/*.sh"]),
)

shellcheck_test(
    name = "shellcheck_all",
    tags = ["lint"],
    targets = [":scripts"],
)

test_suite(
    name = "verify-all",
    tags = ["lint"],
    tests = [
        ":shellcheck_all",
    ],
)
