load("@rules_shell//shell:sh_library.bzl", "sh_library")
load("@rules_shellcheck//:def.bzl", "shellcheck_test")

sh_library(
    name = "lib1",
    srcs = ["lib1.sh"],
    visibility = ["//tests/follow_source:__subpackages__"],
    deps = ["//tests/follow_source/lib2"],
)

shellcheck_test(
    name = "lib1_test",
    targets = [":lib1"],
)
